// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8FbMVuedtjd88XeL8jxc3T60VFmzKDjI',
    appId: '1:994408346996:web:238d6beae60b3f08d0a821',
    messagingSenderId: '994408346996',
    projectId: 'virsaco-prod-rushita',
    authDomain: 'virsaco-prod-rushita.firebaseapp.com',
    storageBucket: 'virsaco-prod-rushita.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9lm4Gqb6WJQUvM3oVJIm4j2RVpImEn28',
    appId: '1:994408346996:android:91a20bd0a0ae664ad0a821',
    messagingSenderId: '994408346996',
    projectId: 'virsaco-prod-rushita',
    storageBucket: 'virsaco-prod-rushita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhyMUoz2KzSEa0aZyvF5ig-wF5-FURV4',
    appId: '1:994408346996:ios:cb081dc19d5ecac6d0a821',
    messagingSenderId: '994408346996',
    projectId: 'virsaco-prod-rushita',
    storageBucket: 'virsaco-prod-rushita.firebasestorage.app',
    iosBundleId: 'com.virsaco.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhyMUoz2KzSEa0aZyvF5ig-wF5-FURV4',
    appId: '1:994408346996:ios:cb081dc19d5ecac6d0a821',
    messagingSenderId: '994408346996',
    projectId: 'virsaco-prod-rushita',
    storageBucket: 'virsaco-prod-rushita.firebasestorage.app',
    iosBundleId: 'com.virsaco.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8FbMVuedtjd88XeL8jxc3T60VFmzKDjI',
    appId: '1:994408346996:web:7e6be9c20ed2f22dd0a821',
    messagingSenderId: '994408346996',
    projectId: 'virsaco-prod-rushita',
    authDomain: 'virsaco-prod-rushita.firebaseapp.com',
    storageBucket: 'virsaco-prod-rushita.firebasestorage.app',
  );

}