// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_test.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgP04_H5YwO6Yzokp6cHETvBlxmoCtNg',
    appId: '1:1098753403739:web:4f64eb572234f0f2a5087e',
    messagingSenderId: '1098753403739',
    projectId: 'virsaco-test-rushita',
    authDomain: 'virsaco-test-rushita.firebaseapp.com',
    storageBucket: 'virsaco-test-rushita.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeOp3Tdw0acpKasd1Uf1zDB6H9T9_gr90',
    appId: '1:1098753403739:android:69c8d21e9e698689a5087e',
    messagingSenderId: '1098753403739',
    projectId: 'virsaco-test-rushita',
    storageBucket: 'virsaco-test-rushita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy-V5L1pJY0VKYQWpsd1h9tiMb9Acgnk0',
    appId: '1:1098753403739:ios:7107178944697fb9a5087e',
    messagingSenderId: '1098753403739',
    projectId: 'virsaco-test-rushita',
    storageBucket: 'virsaco-test-rushita.firebasestorage.app',
    iosBundleId: 'com.virsaco.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy-V5L1pJY0VKYQWpsd1h9tiMb9Acgnk0',
    appId: '1:1098753403739:ios:7107178944697fb9a5087e',
    messagingSenderId: '1098753403739',
    projectId: 'virsaco-test-rushita',
    storageBucket: 'virsaco-test-rushita.firebasestorage.app',
    iosBundleId: 'com.virsaco.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYgP04_H5YwO6Yzokp6cHETvBlxmoCtNg',
    appId: '1:1098753403739:web:c0d9ead5a941e5b8a5087e',
    messagingSenderId: '1098753403739',
    projectId: 'virsaco-test-rushita',
    authDomain: 'virsaco-test-rushita.firebaseapp.com',
    storageBucket: 'virsaco-test-rushita.firebasestorage.app',
  );

}